import { notFound } from "next/navigation";
import { getWorkspace } from "@/lib/workspace";
import { money } from "@/lib/pilot-data";
import { PrintButton } from "./print-button";

export default async function ReceiptPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const { supabase, organizationId } = await getWorkspace();
  const { data: receipt } = await supabase.from("receipts")
    .select("id,receipt_number,issued_at,organizations(name),payments(mpesa_receipt,amount,phone,account_reference,method,received_at,tenants(full_name))")
    .eq("id", id).eq("organization_id", organizationId).maybeSingle();
  if (!receipt) notFound();
  const payment = Array.isArray(receipt.payments) ? receipt.payments[0] : receipt.payments;
  const organization = Array.isArray(receipt.organizations) ? receipt.organizations[0] : receipt.organizations;
  const tenant = Array.isArray(payment?.tenants) ? payment.tenants[0] : payment?.tenants;

  return <div className="receipt-screen">
    <div className="receipt-actions"><a href="/dashboard/receipts">← Back to receipts</a><PrintButton /></div>
    <article className="printable-receipt">
      <header><div className="logo"><span>K</span>Kodi<strong>Flow</strong></div><div><strong>PAYMENT RECEIPT</strong><small>{receipt.receipt_number}</small></div></header>
      <section className="receipt-hero"><span>Amount received</span><strong>{money(Number(payment?.amount ?? 0))}</strong><small>Payment successfully recorded</small></section>
      <dl>
        <div><dt>Landlord / organization</dt><dd>{organization?.name}</dd></div>
        <div><dt>Received from</dt><dd>{tenant?.full_name ?? "Unmatched payer"}</dd></div>
        <div><dt>Tenant account reference</dt><dd>{payment?.account_reference ?? "—"}</dd></div>
        <div><dt>M-Pesa receipt</dt><dd>{payment?.mpesa_receipt ?? "—"}</dd></div>
        <div><dt>Phone</dt><dd>{payment?.phone ?? "—"}</dd></div>
        <div><dt>Payment method</dt><dd>{payment?.method === "mpesa_stk" ? "M-Pesa STK Push" : payment?.method}</dd></div>
        <div><dt>Payment date</dt><dd>{new Date(payment?.received_at ?? receipt.issued_at).toLocaleString("en-KE", { timeZone: "Africa/Nairobi" })}</dd></div>
      </dl>
      <footer><strong>Thank you for your payment.</strong><span>Automatically generated by KodiFlow. No signature is required.</span></footer>
    </article>
  </div>;
}
